In [12]:
#Scalar Tensor (0D)
import tensorflow as tf

scalar = tf.constant(3.0)  # A scalar tensor with value 3.0
print("Scalar:", scalar)
print("Shape:", scalar.shape)

#Vector Tensor (1D)
vector = tf.constant([1.0, 2.0, 3.0])  # A 1D tensor
print("\nVector:", vector)
print("Shape:", vector.shape)


Scalar: tf.Tensor(3.0, shape=(), dtype=float32)
Shape: ()

Vector: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Shape: (3,)


In [13]:
#Matrix Tensor (2D)
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])  # A 2D tensor
print("\nMatrix:\n", matrix)
print("Shape:", matrix.shape)

# Higher-Dimensional Tensor (3D and beyond)
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # A 3D tensor
print("\n3D Tensor:\n", tensor_3d)
print("Shape:", tensor_3d.shape)



Matrix:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)

3D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Shape: (2, 2, 2)


In [15]:
#import tensorflow as tf

# Create two 2D tensors
A = tf.constant([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
B = tf.constant([[7, 8, 9], [10, 11, 12]])  # 2x3 matrix
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

#Addition
C = A + B
print("\nElement-wise Addition:\n", C)

#Subtraction
D = A - B
print("\nElement-wise Subtraction:\n", D)


Matrix A:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Matrix B:
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)

Element-wise Addition:
 tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)

Element-wise Subtraction:
 tf.Tensor(
[[-6 -6 -6]
 [-6 -6 -6]], shape=(2, 3), dtype=int32)


In [16]:

#Multiplication
E = A * B  # Element-wise multiplication (Hadamard product)
print("\nElement-wise Multiplication:\n", E)
 
#Division
F = A / B  # Element-wise division
print("\nElement-wise Division:\n", F)

#Transpose of a Matrix
A_transposed = tf.transpose(A)
print("\nTranspose of A:\n", A_transposed)



Element-wise Multiplication:
 tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32)

Element-wise Division:
 tf.Tensor(
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]], shape=(2, 3), dtype=float64)

Transpose of A:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
